vich_uploader:
    db_driver: orm
    
    #mappings:
    #    products:                                                                  upload mapping a name
    #        uri_prefix: /images/products                                           web path to that directory
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
